### ISSUE TITLE
perPage Pagination Not Rendering Pagination

### ISSUE THREAD

**Issue by N3rdP1um23** [demency/laravel-friendships#1]
Hello,

I was wondering if the pagination is working the same as the normal [Laravel pagination](https://laravel.com/docs/5.8/pagination) where I can place the following into my blade
```
{{ $users->links() }}
or
{{ $user->appends(request()->query())->links() }}
```

I have tested with the above-mentioned blade items, however, I seem to be running into issues. How is the actual `$user->getBlockedFriendships($perPage = 24)` `$perPage` pagination performed and rendered in the blade file?

**Comment by demency** [comment]
Hi @N3rdP1um23 

If you see:

https://github.com/demency/laravel-friendships/blob/866f5021971cab10f6b75e5d60af848923c62606/src/Traits/Friendable.php#L477

You'll check that uses paginate() method of eloquent.

Check this doc:

https://laravel.com/docs/6.x/pagination#displaying-pagination-results

**Comment by N3rdP1um23** [comment]
My mistake, blocked friends don't have the ability to be paginated.

The way I current got around this is by doing the following
```php
use Demency\Friendships\Status;

$user->friends()->whereStatus(Status::BLOCKED)->simplePaginate(24);
```
Where **simplePaginate** can also be **paginate** based off the Laravel Pagination link I posted above.

**Comment by demency** [comment]
friends() method call to relationships, the whereStatus method is a query builder function. 

You're right, this package doens't have methods to call blocked friends using paginate or simplePaginate. Please create other issue and i can help you to add those features :)

**Comment by N3rdP1um23** [comment]
Perfect!  Will do :)   Love the package so far!
