### ISSUE TITLE
Support more versions of Laravel

### ISSUE THREAD

**Issue by demency** [demency/laravel-friendships#12]
In response of #9:

A universal Laravel package of "friends" concept should be great, currently we only support L6.

We need support the last version (Working on #11) and if we want, more oldest releases.

**Comment by omatamix** [comment]
I can add more versions to test against in the pipeline.

**Comment by demency** [comment]
@omatamix pipeline it's done. README.md should be modified i think.

**Comment by omatamix** [comment]
What other versions do you think i should include in the pipeline.

**Comment by demency** [comment]
I think, its ok for now. I mean readme.md must be modified to include the new versions supported on this new pipeline in a table or comment.

If you compare hootlex repository and this repository, just event emitting and testing are different. Old way uses fire method. I dont think if is good support old versions, maybe hootlex can support those versions.

**Comment by omatamix** [comment]
The readme will get updated after I submit the docs PR.

**Comment by omatamix** [comment]
We can probably do 5.8.x and up from here on out.

**Comment by demency** [comment]
Hey I'm back. 

I recently released the v.1.3, supporting more versions. Good work @omatamix !
