### ISSUE TITLE
Class CreateFriendshipsGroupsTable.stub not found

### ISSUE THREAD

**Issue by ayyfahim** [demency/laravel-friendships#18]
![error](https://user-images.githubusercontent.com/61698113/85506610-87aab680-b612-11ea-90cf-a0ef69e97b11.jpg)
When I try to migrate after installing the package I get this error. I am new to Laravel. If anybody can help me with this I would be so grateful.

**Comment by ayyfahim** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/61698113/85508536-166d0280-b616-11ea-8e92-f4f946e199d6.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/61698113/85508537-179e2f80-b616-11ea-83ce-4920f7d29275.jpg)
The migration files were publishing outside the folder so I fixed that. Now I am getting a new error saying class already exists.
![Screenshot_4](https://user-images.githubusercontent.com/61698113/85508619-40262980-b616-11ea-932a-b2fea070a82c.jpg)

**Comment by ayyfahim** [comment]
I have commented out this line, and now the problem is fixed. 

// $this->loadMigrationsFrom(__DIR__ . '/../migrations');

**Comment by demency** [comment]
hey @ayyfahim I'll check that issue in Linux. I think that is because you're using windows and path doesn't works in the same way. 

give some hours and I'll response you!

**Comment by Ahilmurugesan** [comment]
Same issue for me. I am using Linux. 

Any update on this issue?

**Comment by demency** [comment]
I make some changes and a new version was published. I hope this issue this fixed, if not you can comment again and then I'll try to support a fix.
