### ISSUE TITLE
[Request] Paginate Block Friendships

### ISSUE THREAD

**Issue by N3rdP1um23** [demency/laravel-friendships#2]
Hello,

Based on the last [thread](https://github.com/demency/laravel-friendships/issues/1#issuecomment-602649734) could the ability to paginate blocked friends be requested?

Also if possible, the ability to toggle between normal pagination and simple pagination?

**Comment by demency** [comment]
Yeah, i'll this feature in the next release. Give 1 day :)

**Comment by N3rdP1um23** [comment]
Thank you very much and take your time!!  I really appreciate it! :)

**Comment by demency** [comment]
Hi again @N3rdP1um23. That change was added on 1.1 release. Please do composer update and do the new implementations:

> Extracted from README.md

#### Get friends using advanced paginated and scoped status

```php
// Methods usages (Status available: pending, denied, blocked and accepted.)
$user->{status}Friends($resultsPerPage = 0, $paginationType = 'none');

// Example #1: (Get accepted friends using default paginator with 25 results per page).
$user->acceptedFriends(25, 'default');

// Example #2: (Get pending friends using simple paginator with 10 results per page).
$user->pendingFriends(10, 'simple');

// Example #3: (Get all denied friends without pagination).
$user->deniedFriends();

// Example #3: (Get denied friends using default paginator with 30 results per page).
$user->blockedFriends(30);
```

**Comment by N3rdP1um23** [comment]
Hey @demency!

Thank you so much for getting back so quickly I truly appreciate it!  I have updated my composer version successfully as mentioned. However, I have run into the following issue.

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user_id' in 'where clause' (SQL: select count(*) as aggregate from `friendships` where `friendships`.`sender_id` = 1 and `friendships`.`sender_id` is not null and `friendships`.`sender_type` = App\Models\User and `status` = 3 or `user_id` is null
```

The following are the code snippets that I've tried (first is desired and second is testing) but had no luck

```php
$data = $user->blockedFriends($resultsPerPage = 24, $paginationType = 'simple');
$data = $user->blockedFriends(24);
```

The issue from a quick look seems to have come from here (based off the **Unknown column 'user_id' in 'where clause'** error mentioned above)
https://github.com/demency/laravel-friendships/blob/ee526fc733c48e0608e29def77c79aabe61736d5/src/Traits/Friendable.php#L539-L557

**Comment by demency** [comment]
I think sometimes I miss a few lines of code. Thanks, i'll fix this on #5

**Comment by N3rdP1um23** [comment]
@demency Thank you so much for the updated package and also the amazing response!!!! This is an amazing package :)  I'll wait for an official release and let you know how it goes :)

**Comment by demency** [comment]
The release is done, now test the package is your project and close this issue if you think that's close.

**Comment by N3rdP1um23** [comment]
Finally, after composer decided to update/clear cache it was able to update haha.  I have just tested it out and everything is working as expected.  Thanks again for the amazing help, I really appreciate it! :)

**Comment by demency** [comment]
Thanks to you for collaborating. In my case I like to program and interact with other people with code. If you need help let me know.

**Comment by N3rdP1um23** [comment]
My pleasure!  I'm happy that I was able to help and expand the package!!  I will do for sure :)
