### ISSUE TITLE
Is Laravel 7.x supported?

### ISSUE THREAD

**Issue by omatamix** [demency/laravel-friendships#9]

**Comment by demency** [comment]
Composer json have the following key value:

"laravel/laravel": "~7.0 | ~6.0"

Thats allows package installation on projects using 6.x and 7.x. I dont check if that works. After check the travis logs, laravel 6.x is installed by default on build stage. Probably other dependencies like testbench (that package has specific compatibily versions table) blocks the default installation of 7.x (im not sure about that).

**Comment by demency** [comment]
Not for the moment, that solves the issue/question. On #11 should be add the support of L7.
